# Generated by Django 5.0.6 on 2024-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profile_pic.png', upload_to='profile_pics'),
        ),
    ]
