# Generated by Django 5.0.6 on 2024-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
