# Generated by Django 5.0.6 on 2024-07-07 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_doctorroutine_first_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorroutine',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3, unique=True), size=7),
        ),
    ]
