# Generated by Django 5.0.6 on 2024-07-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('routines', '0003_alter_doctorroutine_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorroutine',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.profile'),
        ),
    ]
