# Generated by Django 5.0.6 on 2024-07-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_slotdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorroutine',
            name='first_date',
        ),
        migrations.RemoveField(
            model_name='doctorroutine',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='slotdate',
            name='nextDate',
        ),
        migrations.RemoveField(
            model_name='slotdate',
            name='slot',
        ),
    ]
