# Generated by Django 5.0.6 on 2024-07-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('routines', '0006_remove_doctorroutine_first_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('serial', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('slot_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.slotdate')),
            ],
        ),
    ]
