# Generated by Django 5.0.6 on 2024-07-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
